variables:
  PLUGIN_NAME: SwagMigrationAssistant
  PLATFORM_MIN_VERSION: '6.6.0.0'
  PLATFORM_DEFAULT_VERSION: 'trunk'
  PLATFORM_BRANCH: $PLATFORM_DEFAULT_VERSION
  DEV_IMAGE: shopware/development:8.2-composer-2
  NODE_VERSION: 20

include:
  project: 'shopware/6/product/platform'
  ref: 'trunk'
  file: '.gitlab/templates/plugin.yml'

Danger:
  stage: test
  image:
    name: ghcr.io/shyim/danger-php:latest
    entrypoint: [ "" ]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  before_script: [ ]
  script:
    - danger ci

ecs:
  stage: test
  script:
    - composer ecs

Eslint (administration):
  stage: test
  variables:
    APP_ENV: prod
    ADMIN_PATH: $CI_PROJECT_DIR/src/Administration/Resources/app/administration
    STOREFRONT_PATH: $CI_PROJECT_DIR/src/Storefront/Resources/app/storefront
  script:
    - '(cd $ADMIN_PATH && npm ci)'
    - $CI_PROJECT_DIR/bin/console framework:schema -s 'entity-schema' $ADMIN_PATH/test/_mocks_/entity-schema.json
    - npm --prefix $ADMIN_PATH run unit-setup
    - composer admin:install
    - composer admin:lint

jest (administration):
  rules:
    # exists does not support variables, so we cannot use ${PLUGIN_SOURCE_DIR} here
    - exists:
        - tests/Jest/jest.config.js
  variables:
    APP_ENV: prod
    ADMIN_PATH: $CI_PROJECT_DIR/src/Administration/Resources/app/administration
    STOREFRONT_PATH: $CI_PROJECT_DIR/src/Storefront/Resources/app/storefront
  script:
    - '(cd $ADMIN_PATH && npm ci)'
    - $CI_PROJECT_DIR/bin/console framework:schema -s 'entity-schema' $ADMIN_PATH/test/_mocks_/entity-schema.json
    - npm --prefix $ADMIN_PATH run unit-setup
    - composer admin:install
    - composer admin:unit -- --ci
  coverage: '/^\s?All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      # allow inspection of the coverage report, otherwise it's not accessible
      - custom/plugins/SwagMigrationAssistant/coverage/cobertura-coverage.xml
    reports:
      junit:
        - custom/plugins/SwagMigrationAssistant/coverage/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: custom/plugins/SwagMigrationAssistant/coverage/cobertura-coverage.xml

phpunit:
  script:
    - apt-get update && apt-get --assume-yes install default-mysql-client
    - cd tests
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/services/testdata.git testData
    - cd -
    - mysql -uroot -p"$MYSQL_ROOT_PASSWORD" --host mysql < tests/testData/Migration/sw55.sql
    - php
      -d pcov.enabled=1 -d pcov.directory=$PWD -d pcov.exclude='~(vendor|tests|node_modules)~'
      ${PROJECT_ROOT}/vendor/bin/phpunit
      --configuration phpunit.xml.dist
      --log-junit ${CI_PROJECT_DIR}/phpunit.junit.xml
      --colors=never
      --coverage-cobertura ${CI_PROJECT_DIR}/cobertura.xml
      --coverage-text #| grep -v -E '^Shopware\\|^  Methods:' # do not output covered files lines
  parallel:
    matrix:
      - PLATFORM_BRANCH: [ $PLATFORM_MIN_VERSION, $PLATFORM_DEFAULT_VERSION ]

phpstan:
  script:
    - composer dump-autoload --dev
    - composer phpstan
